//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/ControllLayout.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControllLayout : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControllLayout()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControllLayout"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""aae8a66d-3d91-44fe-908a-744414640a12"",
            ""actions"": [
                {
                    ""name"": ""Speeedup"",
                    ""type"": ""Button"",
                    ""id"": ""631d7b83-92d6-4573-8966-76c27e2a3f12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""slowdown"",
                    ""type"": ""Button"",
                    ""id"": ""1749e517-0275-4d23-99b5-92c6dd7664c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""shoot"",
                    ""type"": ""Button"",
                    ""id"": ""ba47de6d-a4e7-44e9-afc6-299ddb1241dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e9b4c7ea-961e-4535-bea6-935e3c76fa55"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Speeedup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4fe8181-7ad0-4a7d-8911-b5693b22b7c8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""slowdown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""624af6cc-9888-4ec2-ad15-dab913e8a818"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Speeedup = m_Player.FindAction("Speeedup", throwIfNotFound: true);
        m_Player_slowdown = m_Player.FindAction("slowdown", throwIfNotFound: true);
        m_Player_shoot = m_Player.FindAction("shoot", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Speeedup;
    private readonly InputAction m_Player_slowdown;
    private readonly InputAction m_Player_shoot;
    public struct PlayerActions
    {
        private @ControllLayout m_Wrapper;
        public PlayerActions(@ControllLayout wrapper) { m_Wrapper = wrapper; }
        public InputAction @Speeedup => m_Wrapper.m_Player_Speeedup;
        public InputAction @slowdown => m_Wrapper.m_Player_slowdown;
        public InputAction @shoot => m_Wrapper.m_Player_shoot;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Speeedup.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpeeedup;
                @Speeedup.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpeeedup;
                @Speeedup.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpeeedup;
                @slowdown.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSlowdown;
                @slowdown.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSlowdown;
                @slowdown.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSlowdown;
                @shoot.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
                @shoot.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
                @shoot.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Speeedup.started += instance.OnSpeeedup;
                @Speeedup.performed += instance.OnSpeeedup;
                @Speeedup.canceled += instance.OnSpeeedup;
                @slowdown.started += instance.OnSlowdown;
                @slowdown.performed += instance.OnSlowdown;
                @slowdown.canceled += instance.OnSlowdown;
                @shoot.started += instance.OnShoot;
                @shoot.performed += instance.OnShoot;
                @shoot.canceled += instance.OnShoot;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnSpeeedup(InputAction.CallbackContext context);
        void OnSlowdown(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
    }
}
